### ISSUE TITLE
MFTF Test override does not work, if twofactorauth/general/enable is not set at all

### ISSUE THREAD

**Issue by norgeindian** [markshust/magento2-module-disabletwofactorauth#11]
If you run MFTF tests on a system, where the named config setting is not set at all, the override will not work.
To reproduce that, try to log in as an admin, with the settings I mentioned.
This will fail directly.

**Comment by markshust** [comment]
I'll gladly take in a PR which adds unit tests to correct this issue.

**Comment by markshust** [comment]
I believe this has been resolved some time ago in https://github.com/markshust/magento2-module-disabletwofactorauth/pull/16
