### ISSUE TITLE
please make it compatible with php 7.4

### ISSUE THREAD

**Issue by nelero** [markshust/magento2-module-disabletwofactorauth#14]
Hi,
when installing with Magento 2.4.3, composer update failed : 
Package markshust/magento2-module-disabletwofactorauth at version  has a PHP requirement incompatible with your PHP version (7.1.33)

thanks

**Comment by markshust** [comment]
> ...incompatible with your PHP version (7.1.33)

Looks like "your" version is PHP 7.1.33?
