### ISSUE TITLE
System redirect admin/admin/denied/ even module was installed

### ISSUE THREAD

**Issue by tuyennn** [markshust/magento2-module-disabletwofactorauth#15]
Install version 2.0 on "magento/product-enterprise-edition": "2.4.4"
The project is on developer mode

The module doesn't seem to work

**Comment by markshust** [comment]
I'd need more info than that. Error? Logs outputted? etc.

**Comment by tuyennn** [comment]
Well from my point the site still be redirected to admin/admin/denied/ even the module installed or not. The installation of this module took no effect.

**Comment by tuyennn** [comment]
https://github.com/magento/magento2/issues/29884

**Comment by chapagain** [comment]
The admin login redirect was happening on "developer" mode.
I was able to log in when I set the deploy mode to "production"

**Comment by markshust** [comment]
When deploy mode is set to production, this module is bypassed for security reasons, so the regular 2FA process takes effect. 
https://github.com/markshust/magento2-module-disabletwofactorauth/#usage
