### ISSUE TITLE
Cannot access magento.test/admin after installation

### ISSUE THREAD

**Issue by thaingocthienlong** [markshust/magento2-module-disabletwofactorauth#22]
![image](https://github.com/markshust/magento2-module-disabletwofactorauth/assets/118582064/2ff60322-e06b-46c2-8025-8e782598d222)

**Comment by markshust** [comment]
You may want to clear generated code with:

```
rm -rf generated/code
```

It appears something is stale. If you are still getting the error, confirm the file does exist on your filesystem. But this file exists in the normal install of this module https://github.com/markshust/magento2-module-disabletwofactorauth/blob/master/Plugin/BypassTwoFactorAuth.php
