### ISSUE TITLE
PHP7.3 support broken in 1.1.0

### ISSUE THREAD

**Issue by cmacdonald-au** [markshust/magento2-module-disabletwofactorauth#6]
Release 1.1.0 is using PHP 7.4 features but composer references PHP>=7.3

I would submit a PR, but wasn't entirely sure which approach you'd prefer;
 * remove 1.1.0 & do a 2.0.0 for PHP7.4, or
 * strip the types from props for 1.1.1

<3

_Originally posted by @cmacdonald-au in https://github.com/markshust/magento2-module-disabletwofactorauth/issues/4#issuecomment-759257254_

**Comment by markshust** [comment]
Thank you for this. I'll remove the typed properties. Working on it right now.

**Comment by markshust** [comment]
Fixed and tagged version `1.1.1`.
